# Generated by Django 4.0.2 on 2022-08-12 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filmName', models.CharField(max_length=255, verbose_name='Название фильма')),
                ('description', models.TextField(verbose_name='Описание фильма')),
                ('duration', models.TimeField(verbose_name='Продолжительность фильма')),
                ('prewiew', models.ImageField(blank=True, upload_to='imggg')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата выпуска')),
                ('country', models.CharField(max_length=100, verbose_name='Страна')),
            ],
        ),
    ]
