# Generated by Django 4.0.2 on 2022-08-16 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Films', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='videos'),
        ),
        migrations.AddField(
            model_name='film',
            name='rating',
            field=models.IntegerField(default=0, verbose_name='Рейтинг'),
        ),
    ]
