# Generated by Django 4.0.2 on 2022-08-16 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Films', '0003_alter_film_options_alter_film_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='duration',
            field=models.CharField(max_length=20, verbose_name='Продолжительность фильма'),
        ),
    ]
