# Generated by Django 4.0.2 on 2022-08-17 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Films', '0005_alter_film_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='is_for_subscriber',
            field=models.BooleanField(default=False),
        ),
    ]
