# Generated by Django 4.0.2 on 2022-08-17 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Films', '0006_film_is_for_subscriber'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название категории')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.AlterField(
            model_name='film',
            name='is_for_subscriber',
            field=models.BooleanField(default=False, verbose_name='По подписке'),
        ),
        migrations.AddField(
            model_name='film',
            name='category',
            field=models.ManyToManyField(null=True, to='Films.Category', verbose_name='Категория'),
        ),
    ]
